const express = require('express');
const nodemailer = require('nodemailer');
const { database } = require('../database/db');
const { v4: uuidv4 } = require('uuid');
const moment = require('moment');

const router = express.Router();

// Email configuration
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || 'swftagency@gmail.com',
    pass: process.env.EMAIL_PASS || 'hkolxemwgnjvluok'
  }
});

// Fallback email configuration for development
const createTestTransporter = () => {
  return nodemailer.createTransporter({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false,
    auth: {
      user: 'ethereal.user@ethereal.email',
      pass: 'ethereal.pass'
    }
  });
};

// Send email notification
async function sendAppointmentEmail(appointmentData) {
  try {
    const { name, email, phone, company, service, appointment_date, appointment_time, message } = appointmentData;
    
    const emailSubject = `New Appointment Booking - Swift Agency`;
    const emailBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa; border-radius: 10px;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;">
          <h1 style="color: white; margin: 0; font-size: 28px;">Swift Agency</h1>
          <p style="color: white; margin: 10px 0 0 0; font-size: 16px;">New Appointment Booking</p>
        </div>
        
        <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
          <h2 style="color: #333; margin-bottom: 20px; font-size: 24px;">📅 Appointment Details</h2>
          
          <div style="margin-bottom: 30px;">
            <h3 style="color: #667eea; margin-bottom: 15px; font-size: 18px;">👤 Client Information</h3>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555; width: 120px;">Name:</td>
                <td style="padding: 8px 0; color: #333;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555;">Email:</td>
                <td style="padding: 8px 0; color: #333;">${email}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555;">Phone:</td>
                <td style="padding: 8px 0; color: #333;">${phone}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555;">Company:</td>
                <td style="padding: 8px 0; color: #333;">${company || 'Not provided'}</td>
              </tr>
            </table>
          </div>
          
          <div style="margin-bottom: 30px;">
            <h3 style="color: #667eea; margin-bottom: 15px; font-size: 18px;">📋 Appointment Information</h3>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555; width: 120px;">Date:</td>
                <td style="padding: 8px 0; color: #333; font-size: 16px; font-weight: bold;">${appointment_date}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555;">Time:</td>
                <td style="padding: 8px 0; color: #333; font-size: 16px; font-weight: bold;">${appointment_time}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold; color: #555;">Service:</td>
                <td style="padding: 8px 0; color: #333;">${service}</td>
              </tr>
            </table>
          </div>
          
          ${message ? `
          <div style="margin-bottom: 30px;">
            <h3 style="color: #667eea; margin-bottom: 15px; font-size: 18px;">💬 Additional Message</h3>
            <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; border-left: 4px solid #667eea;">
              <p style="margin: 0; color: #555; line-height: 1.6;">${message}</p>
            </div>
          </div>
          ` : ''}
          
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 8px; text-align: center;">
            <p style="color: white; margin: 0; font-size: 16px;">⚡ Please contact the client to confirm this appointment</p>
          </div>
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #666; font-size: 14px;">
          <p>This email was automatically generated by the Swift Agency Booking System</p>
          <p>Booking Time: ${moment().format('MMMM Do YYYY, h:mm:ss a')}</p>
        </div>
      </div>
    `;
    
    const mailOptions = {
      from: process.env.EMAIL_USER || 'noreply@swiftagency.com',
      to: 'anushow299@gmail.com',
      subject: emailSubject,
      html: emailBody,
      replyTo: email
    };
    
    // Try to send with configured transporter, fallback to test transporter
    let emailTransporter = transporter;
    try {
      await emailTransporter.verify();
    } catch (error) {
      console.log('⚠️ Main email service not configured, using test transporter');
      emailTransporter = createTestTransporter();
    }
    
    const info = await emailTransporter.sendMail(mailOptions);
    console.log('✅ Email sent successfully:', info.messageId);
    
    if (emailTransporter === createTestTransporter()) {
      console.log('📧 Preview URL:', nodemailer.getTestMessageUrl(info));
    }
    
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('❌ Error sending email:', error);
    return { success: false, error: error.message };
  }
}

// POST /api/appointments - Create new appointment
router.post('/', async (req, res) => {
  try {
    const { name, email, phone, company, service, appointment_date, appointment_time, message } = req.body;
    
    // Validation
    if (!name || !email || !phone || !service || !appointment_date || !appointment_time) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: name, email, phone, service, appointment_date, appointment_time'
      });
    }
    
    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid email format'
      });
    }
    
    // Validate appointment date (not in the past)
    const appointmentDateTime = moment(`${appointment_date} ${appointment_time}`, 'MMMM Do YYYY h:mm A');
    if (appointmentDateTime.isBefore(moment())) {
      return res.status(400).json({
        success: false,
        error: 'Appointment date and time cannot be in the past'
      });
    }
    
    const appointmentData = {
      name: name.trim(),
      email: email.trim().toLowerCase(),
      phone: phone.trim(),
      company: company ? company.trim() : null,
      service: service.trim(),
      appointment_date: appointment_date.trim(),
      appointment_time: appointment_time.trim(),
      message: message ? message.trim() : null
    };
    
    // Save to database
    const appointment = await database.createAppointment(appointmentData);
    
    // Create or update user
    await database.createOrUpdateUser({
      email: appointmentData.email,
      name: appointmentData.name,
      phone: appointmentData.phone
    });
    
    // Send email notification
    const emailResult = await sendAppointmentEmail(appointmentData);
    
    res.status(201).json({
      success: true,
      message: 'Appointment booked successfully',
      appointment: {
        id: appointment.id,
        ...appointmentData,
        status: 'pending',
        created_at: new Date().toISOString()
      },
      email_sent: emailResult.success,
      email_message_id: emailResult.messageId
    });
    
  } catch (error) {
    console.error('Error creating appointment:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to create appointment',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

// GET /api/appointments - Get all appointments
router.get('/', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 50;
    const appointments = await database.getAppointments(limit);
    
    res.json({
      success: true,
      appointments,
      count: appointments.length
    });
  } catch (error) {
    console.error('Error fetching appointments:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch appointments'
    });
  }
});

// GET /api/appointments/:id - Get specific appointment
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const appointment = await database.getAppointmentById(id);
    
    if (!appointment) {
      return res.status(404).json({
        success: false,
        error: 'Appointment not found'
      });
    }
    
    res.json({
      success: true,
      appointment
    });
  } catch (error) {
    console.error('Error fetching appointment:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch appointment'
    });
  }
});

// PUT /api/appointments/:id/status - Update appointment status
router.put('/:id/status', async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    
    const validStatuses = ['pending', 'confirmed', 'cancelled', 'completed'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        error: `Invalid status. Must be one of: ${validStatuses.join(', ')}`
      });
    }
    
    const result = await database.updateAppointmentStatus(id, status);
    
    if (result.changes === 0) {
      return res.status(404).json({
        success: false,
        error: 'Appointment not found'
      });
    }
    
    res.json({
      success: true,
      message: `Appointment status updated to ${status}`,
      appointment: result
    });
  } catch (error) {
    console.error('Error updating appointment status:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to update appointment status'
    });
  }
});

// GET /api/appointments/available-slots/:date - Get available time slots for a date
router.get('/available-slots/:date', async (req, res) => {
  try {
    const { date } = req.params;
    
    // Business hours: 9 AM to 6 PM, 30-minute slots
    const businessHours = [
      '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
      '12:00', '12:30', '13:00', '13:30', '14:00', '14:30',
      '15:00', '15:30', '16:00', '16:30', '17:00', '17:30'
    ];
    
    // Get booked appointments for this date
    const appointments = await database.getAppointments(100);
    const bookedSlots = appointments
      .filter(apt => apt.appointment_date === date && apt.status !== 'cancelled')
      .map(apt => apt.appointment_time);
    
    // Filter available slots
    const availableSlots = businessHours.filter(slot => !bookedSlots.includes(slot));
    
    // Check if date is today and filter past times
    const today = moment().format('MMMM Do YYYY');
    const isToday = date === today;
    const currentTime = moment();
    
    const filteredSlots = isToday 
      ? availableSlots.filter(slot => {
          const slotTime = moment(slot, 'HH:mm');
          return slotTime.isAfter(currentTime);
        })
      : availableSlots;
    
    res.json({
      success: true,
      date,
      available_slots: filteredSlots,
      booked_slots: bookedSlots,
      total_available: filteredSlots.length
    });
  } catch (error) {
    console.error('Error fetching available slots:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch available slots'
    });
  }
});

module.exports = router;